# Form implementation generated from reading ui file 'welcome_page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 220, 160, 86))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_newproject = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./image/새 프로젝트 버튼.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_newproject.setIcon(icon)
        self.btn_newproject.setObjectName("btn_newproject")
        self.verticalLayout.addWidget(self.btn_newproject)
        self.btn_loadproject = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./image/프로젝트 열기 버튼.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_loadproject.setIcon(icon1)
        self.btn_loadproject.setObjectName("btn_loadproject")
        self.verticalLayout.addWidget(self.btn_loadproject)
        self.btn_setting = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./image/설정 버튼.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_setting.setIcon(icon2)
        self.btn_setting.setObjectName("btn_setting")
        self.verticalLayout.addWidget(self.btn_setting)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 100, 401, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./image/뉴로브릭스-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_newproject.setText(_translate("MainWindow", "  새 프로젝트"))
        self.btn_loadproject.setText(_translate("MainWindow", " 기존 프로젝트 열기"))
        self.btn_setting.setText(_translate("MainWindow", "설정"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
